language: python
python:
  - "3.6"
  - "3.6-dev"

install:
  - pip install codecov
  - pip install pytest pytest-cov
script:
  - python App.py
  - py.test
  - pytest --cov=./

after_success:
  - codecov
